POST http://localhost:3003/user/create 
Content-Type: application/json 

{
    "name": "Paula",
    "email": "campola@email.com",
    "password": "vermelho"
}

#############
POST http://localhost:3003/post/create 
Content-Type: application/json 

{
    "photo": "https://mid.curitiba.pr.gov.br/2015/capa/00159039.jpg",
    "description": "Zombie Walk",
    "type": "event",
    "authorId": "1675392176277" 
}

#####################

GET http://localhost:3003/post/1675392264446
Content-Type: application/json 